name:                HaskellTalk
version:             0.1.0.0
github:              "EoinDavey/HaskellTalk"
license:             BSD3
author:              "Eoin Davey"
maintainer:          "eoind@vey.ie"
copyright:           "2018 Eoin Davey"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/TwitterBot#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- authenticate-oauth
- aeson
- http-conduit
- mtl
- transformers
- random
- containers

library:
  source-dirs: src

executables:
  HaskellTalk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellTalk

tests: {}
